# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: mariadb
    restart: always
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network
    volumes:
      - mariadb-data:/var/lib/mysql
  
  mssql:
    user: 0:0
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
       - 1433:1433
    environment:
       MSSQL_SA_PASSWORD: example@123
       ACCEPT_EULA: Y
       MSSQL_PID: Express
    networks: 
      - internal-container-network
    volumes:
      - /sqlserverdata/Data:/var/opt/mssql/data
      - /sqlserverdata/Log:/var/opt/mssql/log
      - /sqlserverdata/Secrets:/var/opt/mssql/secrets
     
 
   
networks:
  internal-container-network:
    driver: bridge
volumes:
  mariadb-data:
 


  